app_name: notes_app

app_user: app
app_group: app

app_root: /opt/app
app_current_path: /opt/app/current
app_venv_path: /opt/app/venv

app_run_dir: /run/gunicorn
app_bind_host: 0.0.0.0
app_bind_port: 8000
app_workers: 2

app_local_source_path: /home/dev/otushw/hw5/app/

app_env_path: /opt/app/current/.env
app_manage_py_path: /opt/app/current/manage.py
app_wsgi_module: notes_app.wsgi:application

gfs2_mount_point: /srv/shared
shared_static_path: /srv/shared/static
shared_media_path: /srv/shared/media

django_settings_module: notes_app.settings
django_secret_key: "48124812"
django_log_dir: "/var/log/django"
django_allowed_hosts:
  - 127.0.0.1
  - 192.168.1.203
  - localhost

django_csrf_trusted_origins:
  - http://127.0.0.1

# ============================================================
# Подключение к PostgreSQL через HAProxy VIP
# ============================================================
django_db_engine: django.db.backends.postgresql
django_db_name: "{{ db_name }}"                     # берём из postgresql.yml
django_db_user: "{{ db_user }}"                     # берём из postgresql.yml
django_db_password: "{{ db_password }}"             # берём из postgresql.yml
django_db_host: "{{ postgresql_vip }}"              # 192.168.1.100
django_db_port_write: "{{ postgresql_write_port }}" # 5432
django_db_port_read: "{{ postgresql_read_port }}"   # 5433




filebeat_inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
    tags: ["syslog"]
    fields:
      type: syslog
      role: backend
  # Можно добавить логи Django
  - type: log
    enabled: true
    paths:
      - /var/log/django/*.log
    tags: ["django"]
    fields:
      type: django
      role: backend
