[nginx]
nginx-1 ansible_host=192.168.1.201
nginx-2 ansible_host=192.168.1.202

[backend]
backend-1 ansible_host=192.168.1.211
backend-2 ansible_host=192.168.1.212

[cluster:children]
backend


[db]
db-1 ansible_host=192.168.1.221 mysql_server_id=101
db-2 ansible_host=192.168.1.222 mysql_server_id=102
db-3 ansible_host=192.168.1.223 mysql_server_id=103

[mysql_cluster:children]
db

[storage]
storage-1 ansible_host=192.168.1.231


