[angie_b]
vm-1-angie ansible_host=93.77.180.231

[frontends]
vm-2-front-1 ansible_host=10.2.0.5 ansible_ssh_common_args='-o ProxyJump=ubuntu@93.77.180.231'
vm-3-front-2 ansible_host=10.2.0.20 ansible_ssh_common_args='-o ProxyJump=ubuntu@93.77.180.231'

[backend]
vm-4-back-1 ansible_host=10.2.0.29 ansible_ssh_common_args='-o ProxyJump=ubuntu@93.77.180.231'

[all:vars]
ansible_user=ubuntu